<div class="container">
    <div class="row">
        <h2 class="text-center">Status de Publicações</h2>
    </div>
    <a href="/admin/status/novo" class="btn btn-primary pull-left row"><b>+</b> Novo Status</a>
    <div class="row">
        <div class="col-md-6 pull-right row">
            <div id="custom-search-input">
                <?php echo $this->form()->openTag($busca); ?>
                <div class="input-group col-md-12">
                    <?php echo $this->formRow($busca->get('search')); ?>  
                    <span class="input-group-btn">
                        <div style="height: 34px; margin-top:1px;">
                            <button class="btn btn-info btn-sm" type="submit" style="height: 34px; margin-top:-1px;">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </span>
                </div>
                <?php echo $this->form()->closeTag($busca); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" style="margin-top: 5px;">
                <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Editar</th>
                            <th>Deletar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($dados as $value) { ?>
                            <tr>
                                <td><?php echo $value['descricao']; ?></td>
                                <td class="col-md-1"><a class="btn btn-primary btn-xs" data-title="Editar" href="/admin/status/novo/id/<?php echo $value['id']; ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
                                <td class="col-md-1"><a class="btn btn-danger btn-xs" data-title="Deletar" href="/admin/status/delete/id/<?php echo $value['id']; ?>"><span class="glyphicon glyphicon-trash"></span></a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="container row">
    <ul class="pagination">
        <li class="disabled"><a href="#">«</a></li>
        <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">»</a></li>
    </ul>
</div>

<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title custom_align" id="Heading">Edit Your Detail</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <input class="form-control " type="text" placeholder="Tiger Nixon">
                </div>
                <div class="form-group">

                    <input class="form-control " type="text" placeholder="System Architect">
                </div>
                <div class="form-group">


                    <input class="form-control " type="text" placeholder="Edinburgh">

                </div>
            </div>
            <div class="modal-footer ">
                <button type="button" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Update</button>
            </div>
        </div>
    </div>
</div>
