<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/main.js'))
                ->prependFile($this->basePath('js/tinymce/jquery.tinymce.min.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="row col-md-12 pull-right">
                <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
                <div class="alert alert-success">
                <?php foreach ($this->flashMessenger()->getSuccessMessages() as $msg) { ?>
                        <button type="button" class="close" data-dismiss="alert">×</button>    
                        <strong><?php echo $msg; ?></strong>
                <?php } ?>
                </div>
                <?php } ?>
            <!-- Msg Error -->

                <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                <div class="alert alert-danger">
                <?php foreach ($this->flashMessenger()->getErrorMessages() as $msg) { ?>
                        <button type="button" class="close" data-dismiss="alert">×</button>    
                        <strong><?php echo $msg; ?></strong>
                <?php } ?>
                </div>
                <?php } ?>

            <!-- Msg Warning -->

                <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
                <div class="alert alert-warning">
                <?php foreach ($this->flashMessenger()->getInfoMessages() as $msg) { ?>
                        <button type="button" class="close" data-dismiss="alert">×</button>    
                        <strong ><?php echo $msg; ?></strong>
                <?php } ?>
                </div>
                <?php } ?>
        </div>
        <?php echo $this->content; ?>
            <div style="padding-top: 90px;">
            <hr>
            <footer style="text-align: center;">
                <p>&copy; 2015 - <?php echo date('Y') ?> Blog do Alemão Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
            </div>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
