<div class="container">

    <div class="row">
        <div class="col-md-8">
            <h1 class="page-header">
                Blog do Alemão
                <small>Nunca vi Pior</small>
            </h1>
            <?php foreach ($posts as $item) { ?>    
                <h2>
                    <a href="<?php echo '/main/index/ver/id/' . $item['id']; ?>"><?php echo $item['titulo']; ?></a>
                </h2>
                <p><span class="glyphicon glyphicon-time"></span><?php echo ' Publicado em ' . $item['data']->format('d-m-Y H:m:s'); ?></p>
                <hr>
                <a href="<?php echo '/main/index/ver/id/' . $item['id']; ?>" ><img class="img-responsive" src="http://placehold.it/900x300" alt=""></a>
                <hr>
                <p><?php echo $item['mini']; ?></p>
                <a class="btn btn-primary" href="<?php echo '/main/index/ver/id/' . $item['id']; ?>">Leia Mais <span class="glyphicon glyphicon-chevron-right"></span></a>
                <hr>
            <?php } ?>
        </div>

        <div class="col-md-4">
            <div class="well">
                <h4>Pesquise no Blog</h4>
                <div class="input-group">
                    <?php echo $this->form()->openTag($busca); ?>
                    <div class="col-md-12">
                        <?php echo $this->formRow($busca->get('search')); ?>
                    </div>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                    <?php echo $this->form()->closeTag($busca); ?>
                </div>
            </div>
        </div>
    </div> 
</div>
<div class="container row">
    <ul class="pagination">
        <li class="disabled"><a href="#">«</a></li>
        <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">»</a></li>
    </ul>
</div>