<div class="container">
    <div class="row">
        <h2 class="text-center">Usuários</h2>
    </div>
    <a href="/admin/usuarios/novo" class="btn btn-primary pull-left row"><b>+</b> Novo Usuário</a>
    <div class="row">
        <div class="col-md-6 pull-right row">
            <div id="custom-search-input">
                <?php echo $this->form()->openTag($busca); ?>
                <div class="input-group col-md-12">
                    <?php echo $this->formRow($busca->get('search')); ?>  
                    <span class="input-group-btn">
                        <div style="height: 34px; margin-top:1px;">
                            <button class="btn btn-info btn-sm" type="submit" style="height: 34px; margin-top:-1px;">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </span>
                </div>
                <?php echo $this->form()->closeTag($busca); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" style="margin-top: 5px;">
                <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Nascimento</th>
                            <th>Perfil</th>
                            <th>Editar</th>
                            <th>Deletar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($dados as $value) { ?>
                            <tr>
                                <td><?php echo $value['nome']; ?></td>
                                <td><?php echo $value['email']; ?></td>
                                <td><?php echo $value['nascimento']->format('d-m-Y'); ?></td>
                                <td><?php echo $value['perfil']; ?></td>
                                <td class="col-md-1"><a class="btn btn-primary btn-xs" data-title="Editar" href="/admin/usuarios/novo/id/<?php echo $value['id']; ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
                                <td class="col-md-1"><a class="btn btn-danger btn-xs" data-title="Deletar" href="/admin/usuarios/delete/id/<?php echo $value['id']; ?>"><span class="glyphicon glyphicon-trash"></span></a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?php
echo $this->paginationControl($dados, 'Sliding', 'partials/paginator.phtml');