<div class="col-sm-12 col-md-12">
    <div class="col-md-12">
        <h1 class="page-header">Novo Usuário</h1>
    </div>
    <div class="col-md-12">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formRow($form->get('id')); ?>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('nome')); ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('email')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('senha')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('nascimento')); ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('perfil')); ?>
                </div>
            </div>
        </div>
        <div style="text-align: right;">
            <?php echo $this->formSubmit($form->get('salvar')); ?>
            <a class="btn btn-danger" type="button" href="/admin/usuarios">Cancelar</a>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>