<div class="container">
    <div class="row">
        <h2 class="text-center">Publicações do Blog</h2>
    </div>
    <a href="/admin/post/novo" class="btn btn-primary pull-left"><b>+</b> Publicar Novo Post</a>
    <div class="row">
        <div class="col-md-12" style="margin-top: 5px;">
            <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Mini Texto</th>
                        <th>Publicação</th>
<!--                        <th>Status</th>-->
                        <th>Data Publicação</th>
<!--                        <th>Usuário</th>-->
                        <th>Editar</th>
                        <th>Deletar</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dados as $value) { ?>
                        <tr>
                            <td><?php echo $value['titulo']; ?></td>
                            <td><?php echo $value['mini_text']; ?></td>
                            <td><?php echo $value['post_completo']; ?></td>
                            <td><?php echo $value['data_cadastro']->format('d-m-Y'); ?></td>
                            <td>
                                <a href="/admin/post/save/id/<?php echo $value['id']; ?>">Editar</a>
                            </td>
                            <td>
                                <a href="/admin/post/delete/id/<?php echo $value['id']; ?>">Excluir</a>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="container">
    <ul class="pagination">
        <li class="disabled"><a href="#">«</a></li>
        <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">»</a></li>
    </ul>
</div>

<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title custom_align" id="Heading">Edit Your Detail</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <input class="form-control " type="text" placeholder="Tiger Nixon">
                </div>
                <div class="form-group">
                    <input class="form-control " type="text" placeholder="System Architect">
                </div>
                <div class="form-group">
                    <input class="form-control " type="text" placeholder="Edinburgh">
                </div>
            </div>
            <div class="modal-footer ">
                <button type="button" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Update</button>
            </div>
        </div>
    </div>
</div>
<!--


<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title custom_align" id="Heading">Apagar Registro</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Deseja realmente apagar este registro?</div>
            </div>
            <div class="modal-footer ">
                <a type="button" class="btn btn-success" href="/admin/post/delete/id/<?php echo $value['id']; ?>"><span class="glyphicon glyphicon-ok-sign"></span> Sim </a>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Não</button>
            </div>
        </div>
    </div>
</div>-->