<div class="container">
    <div class="row">
        <a class="btn btn-primary btn-lg" href="/admin/posts"><span class="glyphicon glyphicon-pencil"></span> Posts</a>  
        <a class="btn btn-primary btn-lg" href="/admin/usuarios"><span class="glyphicon glyphicon-user"></span> Usuários</a>  
        <a class="btn btn-primary btn-lg" href="/admin/comentarios"><span class="glyphicon glyphicon-comment"></span> Comentários</a>  
        <a class="btn btn-primary btn-lg" href="/admin/status"><span class="glyphicon glyphicon-stats"></span> Status</a>  
    </div>
</div>