<div class="container" style="padding-top: 120px;">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Autenticação</h3>
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form); ?>
                    <fieldset>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('usuario')); ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('senha')); ?>
                        </div>
                        <?php echo $this->formSubmit($form->get('entrar')); ?>
                    </fieldset>
                    <?php echo $this->form()->openTag($form); ?>
                </div>
            </div>
        </div>
    </div>
</div>