<div class="container">
    <div class="row">
        <h2 class="text-center">Publicações do Blog</h2>
    </div>
    <a href="/admin/posts/novo" class="btn btn-primary pull-left row"><b>+</b> Publicar Novo Post</a>
    <div class="row">
        <div class="col-md-6 pull-right row">
            <div id="custom-search-input">
                <?php echo $this->form()->openTag($busca); ?>
                <div class="input-group col-md-12">
                    <?php echo $this->formRow($busca->get('search')); ?>  
                    <span class="input-group-btn">
                        <div style="height: 34px; margin-top:1px;">
                            <button class="btn btn-info btn-sm" type="submit" style="height: 34px; margin-top:-1px;">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </span>
                </div>
                <?php echo $this->form()->closeTag($busca); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" style="margin-top: 5px;">
                <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Mini Texto</th>
                            <th>Publicação</th>
                            <th>Status</th>
                            <th>Data Publicação</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($paginator as $value) { ?>
                            <tr>
                                <td><?php echo $value->getTitulo(); ?></td>
                                <td><?php echo $value->getMiniText(); ?></td>
                                <td><?php echo $value->getPostCompleto(); ?></td>
                                <td><?php echo $value->getStatus()->getDescricao(); ?></td>
                                <td><?php echo $value->getDataCadastro()->format('d-m-Y H:m:s'); ?></td>
                                <td class="col-md-1"><a class="btn btn-primary btn-xs" href="/admin/posts/novo/id/<?php echo $value->getId(); ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
                                <td class="col-md-1"><a class="btn btn-danger btn-xs" href="/admin/posts/delete/id/<?php echo $value->getId(); ?>"><span class="glyphicon glyphicon-trash"></span></a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?php
    echo $this->paginationControl($paginator, 'Sliding', 'partials/paginator.phtml');
?>