<div class="col-sm-12 col-md-12">
    <div class="col-md-12">
        <h1 class="page-header">Novo Post</h1>
    </div>
    <div class="col-md-12">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formRow($form->get('id')); ?>
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('titulo')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('status')); ?>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('data_publicacao')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('resumo')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('postagem')); ?>
                </div>
            </div>
        </div>
        <div style="text-align: right;">
            <?php echo $this->formSubmit($form->get('publicar')); ?>
            <a class="btn btn-danger" type="button" href="/admin/posts">Cancelar</a>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>